// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhnewktbvxcpcpldmzby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJobmV3a3RidnhjcGNwbGRtemJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTkwNTcsImV4cCI6MjA2MzkzNTA1N30.vU0BFSCnOf1LTVj6GuA3i2gsKk5sYdggCj1p-45Mg6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);